### ISSUE TITLE
IndexError with plane_history

### ISSUE THREAD

**Issue by vpatil33** [quantumbagel/airstrik.py#1]
```
Traceback (most recent call last):
  File "airstrik.py", line 695, in <module>
     hexes = collect_data(aircraft_json, plane_history)  # Update data
  File "airstrik.py", line 504, in collect_data
     if kval[1] <= closest_time:
IndexError: string index out of range
```

After running airstrik.py for about ~10 min, I receive this error consistently. I used docker compose to run the service. I've noticed the error is more likely to occur when there are more planes, as I have run the program at midnight (when there are much fewer planes) and I have not encountered this error.

I did make a modification to the airstrik.py file: removed lines 347 & 364 so that I get both console output and kafka output. Thus, the line numbers in the error message are offset by 2 compared to the latest version on Github. (695 -> 697, 504 -> 506)

**Comment by quantumbagel** [comment]
Hi Vaibhav!

First thing: this program is a little bit of a buggy mess, so it may just be doing some funky stuff it shouldn't be doing :)

I'm writing a replacement for this code (PyAerial) that avoids interfacing with dump1090 and is overall much better in my testing. However, it's still in development and doesn't have all of the features that airstrik does currently. 

The code segment that's crashing, for reference:
![image](https://github.com/quantumbagel/airstrik.py/assets/58365715/5a0c564e-e82e-4b59-834f-ff564691856f)

My best guess for what's going on here is this:

`kval` is simply each data point (value, time). The code here is determining the closest data point from each type (altitude, latitude, longitude) to the time (`closest_time`) where the plane is closest to the sensor by distance. It seems like `kval` is getting set to either an empty string or 1-length string, which should (obviously) never happen. Please add this line after `                    for kval in plane_history[aircraft['hex']][item][::-1]:`: 

`print(kval, type(kval), item, plane_history[aircraft['hex']][item][::-1])`

Please let me know what this addition prints.

Thanks for catching this!

**Comment by vpatil33** [comment]
```
 ['N401NC', 1710446394.3] <class 'list'> flight_name_id [['N401NC', 1710446394.3]]
 7 <class 'str'> flight_id 781b4a
```
I get the above output before the program crashes. It looks like the first line is a valid case, with the format [data, time]. However, the second line shows kval getting set to a 1-length string: "7" as you said, which is causing the error. Since flight_id isn't really a data point (it doesn't change), I assume it should be ignored?

**Comment by quantumbagel** [comment]
I've pushed a patch for this bug. Please try again and see if this fixes the issue.
